### ISSUE TITLE
Installation Issue: undefined reference to `Minisat::SimpSolver::addClause_(Minisat::vec<Minisat::Lit, int>&)'

### ISSUE THREAD

**Issue by Anonychn** [stp/stp#432]
Hi, I am using ubuntu 20.04. I tried to install STP with `cryptominisat `as a SAT solver but some issues occurs. The list of commands that I executed is as follows: 

```
sudo apt-get install cmake bison flex libboost-all-dev python perl minisat
git clone https://github.com/stp/minisat
cd minisat
mkdir build && cd build
cmake ..
cmake --build .
sudo cmake --install .
command -v ldconfig && sudo ldconfig

cd ~

git clone https://github.com/msoos/cryptominisat
cd cryptominisat
mkdir build && cd build
cmake ..
cmake --build .
sudo cmake --install .
command -v ldconfig && sudo ldconfig

cd ~

git clone https://github.com/stp/stp
cd stp
git submodule update --init
pip install lit
./scripts/deps/setup-gtest.sh
./scripts/deps/setup-outputcheck.sh
mkdir build
cd build
cmake -DENABLE_TESTING=ON ..
make
```

After make command I faced the following errors:

```
usr/bin/ld: ../../lib/libstp.so.2.3: undefined reference to `Minisat::SimpSolver::addClause_(Minisat::vec<Minisat::Lit, int>&)'
/usr/bin/ld: ../../lib/libstp.so.2.3: undefined reference to `Minisat::Solver::addClause_(Minisat::vec<Minisat::Lit, int>&)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/stp/CMakeFiles/stp-bin.dir/build.make:105: stp] Error 1
make[1]: *** [CMakeFiles/Makefile2:1382: tools/stp/CMakeFiles/stp-bin.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

I am not sure how to resolve these errors. I would be thankful if anyone can help me out.

**Comment by msoos** [comment]
Hi,

Sorry for your inconvenience.

I think you may have trouble because you also had another version of MiniSat installed. Can you please try to remove MiniSat from your system and then re-do the above? I think the `SimpSolver` in the MiniSat library that you have installed is different or it simply does not contain the `SimpSolver` part (only the non-simplifying solver).

I'd also suggest to send us the output of `ldd ../../lib/libstp.so.2.3` and check if that output is what you'd expect, i.e. if that file's timestamp is indeed recent, i.e. what you have just installed. My guess is that it's not, and it's a library you built and installed for some other reason. 

Let us know if the above helped,

Mate

**Comment by Anonychn** [comment]
Still the same error. I executed the following code:
```
sudo apt remove minisat
sudo apt autoclean && sudo apt autoremove
```

After that, I repeated the aforementioned code but after `make` the same set of errors occurred.


Output of `ldd /stp/build/lib/libstp.so.2.3` is 
```
linux-vdso.so.1 (0x00007ffd3d744000)
	libminisat.so.2 => /home/linuxbrew/.linuxbrew/lib/libminisat.so.2 (0x00007fbfd0f2f000)
	libcryptominisat5.so.5.8 => /home/linuxbrew/.linuxbrew/lib/libcryptominisat5.so.5.8 (0x00007fbfd0c37000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbfd0a3c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbfd08ed000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbfd08d2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbfd08af000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbfd06bb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbfd140e000)
	libsqlite3.so.0 => /home/linuxbrew/.linuxbrew/lib/../lib/libsqlite3.so.0 (0x00007fbfd0379000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbfd0371000)

```
For timestamp, I executed `stat libstp.so.2.3` and the output is 
```
File: libstp.so.2.3
  Size: 41400064  	Blocks: 80864      IO Block: 4096   regular file
Device: 10304h/66308d	Inode: 11146760    Links: 1
Access: (0775/-rwxrwxr-x)  Uid: ( 1000/  satyam)   Gid: ( 1000/  satyam)
Access: 2022-07-11 15:34:43.729228889 +0530
Modify: 2022-07-11 15:34:37.152483679 +0530
Change: 2022-07-11 15:34:37.152483679 +0530

```

**Comment by aytey** [comment]
When you run:

```
sudo cmake --install .
```

Does it tell you where it is installing to? I don't see anything in your CMake invocation that would say to install to `/home/linuxbrew/.linuxbrew`.

Based on the output you shared, you *also* have `minisat` and CMS installed via `linuxbrew`.

Can you try removing these packages as well?

**Comment by Anonychn** [comment]
I deleted the following files:
```
libminisat.so.2 => /home/linuxbrew/.linuxbrew/lib/libminisat.so.2 (0x00007fbfd0f2f000)
	libcryptominisat5.so.5.8 => /home/linuxbrew/.linuxbrew/lib/libcryptominisat5.so.5.8 (0x00007fbfd0c37000)
```
Removed the folder cryptominisat, minisat and stp. After that I repeated the same procedure as given in the question but still facing the same error.

The output of `ldd libstp.so.2.3` after make command:
```
        linux-vdso.so.1 (0x00007ffd13cfa000)
	libminisat.so.2 => /usr/local/lib/libminisat.so.2 (0x00007f14262da000)
	libcryptominisat5.so.5.8 => /usr/local/lib/libcryptominisat5.so.5.8 (0x00007f14261cb000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1425fd0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1425e81000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1425e66000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1425e43000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1425c4f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f14265d5000)
	libm4ri-0.0.20200125.so => /lib/x86_64-linux-gnu/libm4ri-0.0.20200125.so (0x00007f1425c1a000)
	libsqlite3.so.0 => /lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f1425af1000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f1425ab9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1425ab3000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1425a95000)
```

During executing `cmake -DENABLE_TESTING=ON ..` I encountered some warnings that might be relevant to this problem. Since I  could not understand how to rectify the error, so I am posting the output below
```
-- The following features have been disabled:

 * Sanitizers, Enables Clang sanitizers, will force using clang++ as the compiler
 * Static, Compiles static library and executable
 * SimpleOptions, Simplifies command-line interface, only a few command-line options will be available
 * Riss, Enables Riss solver

-- Configuring done
CMake Warning at lib/CMakeLists.txt:90 (add_library):
  Cannot generate a safe runtime search path for target stp because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.


CMake Warning at tools/stp/CMakeLists.txt:25 (add_executable):
  Cannot generate a safe runtime search path for target stp-bin because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.


CMake Warning at tools/stp_simple/CMakeLists.txt:25 (add_executable):
  Cannot generate a safe runtime search path for target stp_simple-bin
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target check_sizesTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:67 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target bit_stringTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:66 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  failing_solvermapTests because files in some directories may conflict with
  libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:65 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  counter-example-readingTests because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:64 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target counterexampleTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:62 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target mdempskyTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:61 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target stp-boolTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:46 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target example_brokenTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:63 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  parsestring-using-cinterfaceTests because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:38 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target sbvdivTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:43 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target printTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:39 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target multi-query-bugTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:58 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target multiple-queriesTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:34 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target stp-array-modelTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:45 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target getbvTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:29 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  parsefile-using-cinterfaceTests because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:35 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target if-checkTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:31 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target xTests because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:56 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target reported_errorTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:59 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target hoangmleTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:30 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target array-iteTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:26 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target b4-cTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:28 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target interface-checkTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:32 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target push-no-popTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:41 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target b4-c2Tests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:27 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target push-popTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:42 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target stpcheckTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:47 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target stp-counterexTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:48 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target array-cvcl-02Tests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:25 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target multi-printTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:40 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target simplifyTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:44 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target stp-div-001Tests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:49 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target stp-test3Tests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:50 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target yTests because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:57 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target leaksTests because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:33 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  stp-even-eqn-assertTests because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/api/C/CMakeLists.txt:60 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  PropagateEqualities_TestTests because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/unit-tests/CMakeLists.txt:25 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target Flatten_TestTests
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/unit-tests/CMakeLists.txt:28 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  SimplifyingNodeFactory_TestTests because files in some directories may
  conflict with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/unit-tests/CMakeLists.txt:26 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  SplitExtracts_TestTests because files in some directories may conflict with
  libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/unit-tests/CMakeLists.txt:30 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  StrengthReduction_TestTests because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/unit-tests/CMakeLists.txt:31 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  FindPureLiterals_TestTests because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/unit-tests/CMakeLists.txt:27 (AddSTPGTest)


CMake Warning at cmake/modules/AddSTPGTest.cmake:39 (add_executable):
  Cannot generate a safe runtime search path for target
  NodeDomainAnalysis_TestTests because files in some directories may conflict
  with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/unit-tests/CMakeLists.txt:29 (AddSTPGTest)

```

**Comment by rgov** [comment]
I think you edited your post but this warning from CMake is probably a strong hint to what is wrong:

```
CMake Warning at lib/CMakeLists.txt:90 (add_library):
  Cannot generate a safe runtime search path for target stp because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libminisat.so.2] in /lib may be hidden by files in:
      /usr/local/lib

  Some of these libraries may not be found correctly.
```

You have `/usr/local/lib/libminisat*` and `/lib/libminisat*`. You probably didn't mean to install it in `/lib`. Ideally you would delete both and install again, and only in `/usr/local/lib`, which is the correct place to put software that you build and install manually on the system.

**Comment by Anonychn** [comment]
Thanks for considering the question. I did a minor change in the question that I missed earlier, i.e., I added `cd stp`.

I think by `/lib/libminisat*` you are referring to `stp/build/lib/libminisat*` as it is the path where executed `cmake`. But when I check there is no `libminisat*` files at `stp/build/lib/`. The only files present at this positions are 
```
AbsRefineCounterExample  CMakeFiles           extlib-abc      Globals    libstp.so      Makefile     Parser   Sat         STPManager  Util
AST                      cmake_install.cmake  extlib-constbv  Interface  libstp.so.2.3  NodeFactory  Printer  Simplifier  ToSat

```
Upon exploring the above folders, the only relevant files I found are under `./Sat/CMakeFiles/sat.dir/`
```
 CryptoMinisat5.cpp.o
MinisatCore.cpp.o
SimplifyingMinisat.cpp.o
```

At the position `/usr/local/lib/libminisat*` I can find the following relevant files:
```
libcryptominisat5.so            
libcryptominisat5.so.5.8       
libminisat.so
libminisat.so.2
libminisat.so.2.1.0
```
Not sure which file to delete in `stp/build/lib/libminisat*`. 

Additionally, I tried to pass the path as an argument during `cmake` as follows and I did not received the earlier warning but received the same error as in question during `make`.

```
cmake -DENABLE_TESTING=ON -DMINISAT_INCLUDE_DIRS:PATH=/home/satyam/minisat/minisat/core/ -DMINISAT_LIBDIR:PATH=/home/satyam/minisat/build/ -Dcryptominisat5_DIR:PATH=/home/satyam/cryptominisat/build/ ..
```

**Comment by Anonychn** [comment]
Hi, I think I have installed stp correctly as I found a similar issue: https://github.com/stp/stp/issues/382 
However, when I tried to run it, I am facing some errors.
First I create a file `test.smt` which contains (some standard examples in SMTLIB2 format)
```
(set-logic QF_BV)
(set-info :smt-lib-version 2.0)
(set-info :status sat)
(assert (= (bvsdiv (_ bv3 2) (_ bv2 2)) (_ bv0 2)))
(check-sat)
(exit)
```
After executing `stp test.smt` I faced the following errors: 
```
syntax error: line 1
syntax error, unexpected STRING_TOK, expecting BENCHMARK_TOK
  token: set
Fatal Error: 
STP Error: 
```

Whereas I tried `import stp` in python3 which gives error as follows:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/satyam/STP_solver/lib/python3.8/site-packages/stp/__init__.py", line 26, in <module>
    from .stp import (
  File "/home/satyam/STP_solver/lib/python3.8/site-packages/stp/stp.py", line 45, in <module>
    from library_path import PATHS
ModuleNotFoundError: No module named 'library_path'
```
and pip could not find `library_path`.

**Comment by aytey** [comment]
> After executing stp test.smt I faced the following errors:
>

Can you try naming your file `.smt2` and not `.smt`?

> and pip could not find library_path.
>

`library_path` is an STP library; it should be next to `stp.py` -- can you check if it is there?

**Comment by Anonychn** [comment]
Thanks renaming the file extension with `.smt2` worked.

`stp.py` is at two locations `/home/satyam/stp/build/bindings/python/stp` and `/home/satyam/STP_solver/lib/python3.8/site-packages/stp`, where `STP_solver` is a python virtual environment ( I installed stp in a python3 virtual environment.
Both location contains `lilbrary_path.py` files. But I am not sure what to do to make it work in python3, since I am a beginner in linux.

**Comment by Anonychn** [comment]
@rgov 
Still receiving the error as follows:
```
>>> import pprint
>>> import sys
>>> import stp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/satyam/STP_solver/lib/python3.8/site-packages/stp/__init__.py", line 26, in <module>
    from .stp import (
  File "/home/satyam/STP_solver/lib/python3.8/site-packages/stp/stp.py", line 45, in <module>
    from library_path import PATHS
ModuleNotFoundError: No module named 'library_path'
>>> print(stp._path_)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'stp' is not defined
>>> pprint.pprint(sys.path)
['',
 '/usr/lib/python38.zip',
 '/usr/lib/python3.8',
 '/usr/lib/python3.8/lib-dynload',
 '/home/satyam/STP_solver/lib/python3.8/site-packages']
```

**Comment by aytey** [comment]
This isn't a good fix, but if you add `/home/satyam/STP_solver/lib/python3.8/site-packages/stp` to `PYTHONPATH`, does it now work?

**Comment by Anonychn** [comment]
> /home/satyam/STP_solver/lib/python3.8/site-packages/stp
Thanks the problem is resolved now.
