### ISSUE TITLE
No module named 'library_path'

### ISSUE THREAD

**Issue by learnerLj** [stp/stp#454]
I followed the instruction in  README and built `stp` on Ubuntu 22.04 LTS on VMware. I encounter the same problem #446 and addressed it with the advice https://github.com/stp/stp/issues/446#issuecomment-1236503061 . Finally, the installation is successful.
```
[100%] Built target stp_simple-bin
-- Install configuration: "RelWithDebInfo"
-- Up-to-date: /usr/local/lib/cmake/STP/STPConfig.cmake
-- Up-to-date: /usr/local/lib/cmake/STP/STPConfigVersion.cmake
-- Up-to-date: /usr/local/lib/cmake/STP/STPTargets.cmake
-- Up-to-date: /usr/local/lib/cmake/STP/STPTargets-relwithdebinfo.cmake
-- Installing: /usr/local/lib/libstp.so.2.3
-- Set runtime path of "/usr/local/lib/libstp.so.2.3" to "lib"
-- Installing: /usr/local/lib/libstp.so
-- Installing: /usr/local/include/stp/c_interface.h
-- Installing: /usr/local/bin/stp
-- Set runtime path of "/usr/local/bin/stp" to "lib"
-- Installing: /usr/local/bin/stp_simple
-- Set runtime path of "/usr/local/bin/stp_simple" to "lib"
-- Installing: /home/learner/tools/anaconda3/lib/python3.9/site-packages/stp/stp.py
-- Installing: /home/learner/tools/anaconda3/lib/python3.9/site-packages/stp/__init__.py
-- Installing: /home/learner/tools/anaconda3/lib/python3.9/site-packages/stp/library_path.py
```
However, it throws an error when I import `stp`  in python. the error shows that
```
(base) ➜  build git:(master) ✗ python
Python 3.9.13 (main, Aug 25 2022, 23:26:10)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/learner/tools/anaconda3/lib/python3.9/site-packages/stp/__init__.py", line 26, in <module>
    from .stp import (
  File "/home/learner/tools/anaconda3/lib/python3.9/site-packages/stp/stp.py", line 45, in <module>
    from library_path import PATHS
ModuleNotFoundError: No module named 'library_path'
```
I do not find any package named `library_path` at PyPI or conda.

**Comment by rgov** [comment]
If you edit `/home/learner/tools/anaconda3/lib/python3.9/site-packages/stp/stp.py` to change line 45 to

    from .library_path import PATHS

does it have the same issue?

**Comment by learnerLj** [comment]
> If you edit `/home/learner/tools/anaconda3/lib/python3.9/site-packages/stp/stp.py` to change line 45 to
> 
> ```
> from .library_path import PATHS
> ```
> 
> does it have the same issue?

Thanks! It works.

**Comment by SJTUwwz** [comment]
Hello！I try to edit the line 45 in stp.py, but I meet another error unfortunely. 

>>> import stp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/lib/python3.9/site-packages/stp/stp.py", line 45, in <module>
    from .library_path import PATHS
ImportError: attempted relative import with no known parent package

Could you please help me figure it out?
